title: ConnorBP ./ Segfault
logo: /thisisfine.png
description: ConnorBP is pretty cool i guess...
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- github-pages